// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;

namespace OptTorgWebDB.Models;

public partial class Buys
{
    public long IdBuys { get; set; }

    public long ProductId { get; set; }

    public long SupplierId { get; set; }

    public int Count { get; set; }

    public bool Active { get; set; }

    public virtual Products Product { get; set; }

    public virtual ICollection<ProductPart> ProductPart { get; set; } = new List<ProductPart>();

    public virtual Suppliers Supplier { get; set; }

    public static List<Buys> GetAllBuys()
    {
        var db = new OptTorgDBContext();
        var p = db.Buys
            .Where(x => x.Active == true)
            .Include(x=> x.Product)
            .Include(x => x.Supplier);

        return p.ToList();
    }

    public static Buys GetNavData(Buys b)
    {
        var db = new OptTorgDBContext();
        b.Product = db.Products.Single(x => x.IdProduct == b.ProductId);
        b.Supplier = db.Suppliers.Single(x => x.IdSuppliers == b.SupplierId);

        return b;
    }

    public static void CreatrBuys(Buys p)
    {
        var db = new OptTorgDBContext();
        p.Active = true;
        p.Supplier = null;
        p.Product = null;
        db.Buys.Add(p);

        db.SaveChanges();
    }

    public static Buys GetBuysById(int id)
    {
        var db = new OptTorgDBContext();
        return db.Buys.Single(x => x.IdBuys == id);
    }

    public static void UpdateBuys(Buys p)
    {
        var db = new OptTorgDBContext();
        p.Active = true;

        db.Buys.Update(p);

        db.SaveChanges();
    }

    public static void DeleteBuys(int id)
    {
        var db = new OptTorgDBContext();
        var pos = db.Buys.FirstOrDefault(x => x.IdBuys == id);
        pos.Active = false;

        db.SaveChanges();
    }
}