// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OptTorgWebDB.Models;

public partial class Buys
{
    public long IdBuys { get; set; }

    public long ProductId { get; set; }

    public long SupplierId { get; set; }

    public int Count { get; set; }

    public virtual Products Product { get; set; }

    public virtual ICollection<ProductPart> ProductPart { get; set; } = new List<ProductPart>();

    public virtual Suppliers Supplier { get; set; }
}