// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using OptTorgWeb.Classes;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace OptTorgWebDB.Models;

public partial class CargoInfo
{
    [Required(ErrorMessage = ErrorMessages.IsRequired)]
    public long IdCargoInfo { get; set; }

    [Required(ErrorMessage = ErrorMessages.IsRequired)]
    public long SaleId { get; set; }

    [Required(ErrorMessage = ErrorMessages.IsRequired)]
    public long SendingId { get; set; }

    [Required(ErrorMessage = ErrorMessages.IsRequired)]
    [Range(1, int.MaxValue, ErrorMessage = "Значение должно быть больше 0.")]
    [RegularExpression(@"^\d+$", ErrorMessage = "Допустимы только цифры.")]
    public int Count { get; set; }

    public virtual Sales Sale { get; set; }

    public virtual Sending Sending { get; set; }

    public static List<CargoInfo> GetAllCargoInfo()
    {
        var db = new OptTorgDBContext();
        var p = db.CargoInfo
            .Include(x => x.Sending.Transport)
            .Include(x => x.Sending.GlavBuh)
            .Include(x => x.Sending.Driver.SeNavigation.EmployeeNavigation)
            .Include(x => x.Sending.Ss)
            .Include(x => x.Sale.Product)
            .Include(x => x.Sale.Customer)
            /*.Where(x => x.Active == true)*/;

        return p.ToList();
    }

    public static List<CargoInfo> GetAllCustomerCargoInfo(long id)
    {
        var db = new OptTorgDBContext();
        var p = db.CargoInfo
            .Include(x => x.Sending.Transport)
            .Include(x => x.Sending.GlavBuh)
            .Include(x => x.Sending.Driver.SeNavigation.EmployeeNavigation)
            .Include(x => x.Sending.Ss)
            .Include(x => x.Sale.Product)
            .Include(x => x.Sale.Customer)
            .Where(x => x.Sale.CustomerId == id);  
            /*.Where(x => x.Active == true)*/;

        return p.ToList();
    }

    public static void CreatrCargoInfo(CargoInfo p)
    {
        var db = new OptTorgDBContext();
        p.Sending = null;
        p.Sale = null;
        //p.Active = true;

        db.CargoInfo.Add(p);

        db.SaveChanges();
    }

    
    public static List<CargoInfo> GetCargoInfoForSending(long id)
    {
        var db = new OptTorgDBContext();
        var p = db.CargoInfo
            .Include(x => x.Sending.Transport)
            .Include(x => x.Sending.GlavBuh)
            .Include(x => x.Sending.Driver.SeNavigation.EmployeeNavigation)
            .Include(x => x.Sending.Ss)
            .Include(x => x.Sale.Product)
            .Include(x => x.Sale.Customer)
            .Where(x => x.SendingId == id);

        return p.ToList();
    }
    public static void DeleteCargoInfo(long id)
    {
        var db = new OptTorgDBContext();
        var pos = db.CargoInfo.FirstOrDefault(x => x.IdCargoInfo == id);
        //pos.Active = false;

        db.SaveChanges();
    }

    public static void DCascade(int id)
    {
        var db = new OptTorgDBContext();
        var strg = db.CargoInfo.FirstOrDefault(x => x.IdCargoInfo == id);

        db.Remove(strg);
        db.SaveChanges();
    }
}