// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OptTorgWebDB.Models;

public partial class CargoInfo
{
    public long IdCargoInfo { get; set; }

    public long SaleId { get; set; }

    public long SendingId { get; set; }

    public int Count { get; set; }

    public virtual Sales Sale { get; set; }

    public virtual Sending Sending { get; set; }
}