// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OptTorgWebDB.Models;

public partial class CountryOfProduct
{
    public long IdCof { get; set; }

    public string NumericCode { get; set; }

    public string ShortName { get; set; }

    public virtual ICollection<Products> Products { get; set; } = new List<Products>();
}