// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OptTorgWebDB.Models;

public partial class Customers
{
    public long IdCustomers { get; set; }

    public string Company { get; set; }

    public string Surname { get; set; }

    public string Name { get; set; }

    public string Patronomuc { get; set; }

    public string Position { get; set; }

    public string Adress { get; set; }

    public string City { get; set; }

    public string Oblast { get; set; }

    public int PostIndex { get; set; }

    public string State { get; set; }

    public int? Fax { get; set; }

    public string Phone { get; set; }

    public int Inn { get; set; }
    public bool Active { get; set; }
    public string WebPage { get; set; }

    public virtual ICollection<Sending> Sending { get; set; } = new List<Sending>();

    public static List<Customers> GetAllCustomers()
    {
        var db = new OptTorgDBContext();
        return db.Customers.Where(x => x.Active == true).ToList();
    }

    public static void CreatrCustomers(Customers p)
    {
        var db = new OptTorgDBContext();
        p.Active = true;
        db.Customers.Add(p);
        db.SaveChanges();
    }

    public static Customers GetCustomersById(int id)
    {
        var db = new OptTorgDBContext();
        return db.Customers.Single(x => x.IdCustomers == id);
    }

    public static void UpdateCustomers(Customers p)
    {
        var db = new OptTorgDBContext();
        db.Customers.Update(p);
        db.SaveChanges();
    }

    public static void DeleteCustomers(int id)
    {
        var db = new OptTorgDBContext();
        var pos = db.Customers.FirstOrDefault(x => x.IdCustomers == id);
        pos.Active = false;

        db.SaveChanges();
    }
}