// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OptTorgWebDB.Models;

public partial class Delivery
{
    public long IdDelivery { get; set; }

    public long EmployeeReceiveId { get; set; }

    public long EmployeeAcceptId { get; set; }

    public long StorageId { get; set; }

    public long TransportId { get; set; }

    public long StatusId { get; set; }

    public long DriverId { get; set; }

    public string Osnovanie { get; set; }

    public DateOnly Date { get; set; }

    public string NomerDoverennosti { get; set; }

    public virtual Drivers Driver { get; set; }

    public virtual Employees EmployeeAccept { get; set; }

    public virtual Employees EmployeeReceive { get; set; }

    public virtual ICollection<ProductPart> ProductPart { get; set; } = new List<ProductPart>();

    public virtual DeliveryStatus Status { get; set; }

    public virtual Storages Storage { get; set; }

    public virtual Transport Transport { get; set; }
}