// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using OptTorgWeb.Classes;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace OptTorgWebDB.Models;

public partial class DeliveryStatus
{
    [Required(ErrorMessage = ErrorMessages.IsRequired)]
    public long IdDs { get; set; }

    [Required(ErrorMessage = ErrorMessages.IsRequired)]
    [RegularExpression(@"^[а-яА-Я]+$", ErrorMessage = ErrorMessages.OnlyRuLetters)]
    [MinLength(3, ErrorMessage = "Введенное значение слишком короткое. Минимальная длинна - 3 символа")]
    public string Status { get; set; }

    public bool Active { get; set; }

    public virtual ICollection<Delivery> Delivery { get; set; } = new List<Delivery>();


    public static List<DeliveryStatus> GetAllDeliveryStatus()
    {
        var db = new OptTorgDBContext();
        var dsList = db.DeliveryStatus.Where(x => x.Active == true).ToList();
        
        return dsList;
    }
    public static void CreatrPosition(DeliveryStatus p)
    {
        var db = new OptTorgDBContext();
        p.Active = true;
        db.DeliveryStatus.Add(p);
        db.SaveChanges();
    }
    public static DeliveryStatus GetPositionById(int id)
    {
        var db = new OptTorgDBContext();
        return db.DeliveryStatus.Single(x => x.IdDs == id);
    }
    public static void UpdatePosition(DeliveryStatus p)
    {
        var db = new OptTorgDBContext();
        p.Active = true;
        db.DeliveryStatus.Update(p);
        db.SaveChanges();
    }
    public static void DeletePosition(int id)
    {
        var db = new OptTorgDBContext();
        var pos = db.DeliveryStatus.FirstOrDefault(x => x.IdDs == id);
        pos.Active = false;

        db.SaveChanges();
    }
    public static void DCascade(int id)
    {
        var db = new OptTorgDBContext();
        var strg = db.DeliveryStatus.FirstOrDefault(x => x.IdDs == id);

        db.Remove(strg);
        db.SaveChanges();
    }
}