// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OptTorgWebDB.Models;

public partial class DeliveryStatus
{
    public long IdDs { get; set; }

    public string Status { get; set; }

    public bool Active { get; set; }

    public virtual ICollection<Delivery> Delivery { get; set; } = new List<Delivery>();


    public static List<DeliveryStatus> GetAllDeliveryStatus()
    {
        var db = new OptTorgDBContext();
        return db.DeliveryStatus.Where(x => x.Active == true).ToList();
    }
    public static void CreatrPosition(DeliveryStatus p)
    {
        var db = new OptTorgDBContext();
        p.Active = true;
        db.DeliveryStatus.Add(p);
        db.SaveChanges();
    }
    public static DeliveryStatus GetPositionById(int id)
    {
        var db = new OptTorgDBContext();
        return db.DeliveryStatus.Single(x => x.IdDs == id);
    }
    public static void UpdatePosition(DeliveryStatus p)
    {
        var db = new OptTorgDBContext();
        p.Active = true;
        db.DeliveryStatus.Update(p);
        db.SaveChanges();
    }
    public static void DeletePosition(int id)
    {
        var db = new OptTorgDBContext();
        var pos = db.DeliveryStatus.FirstOrDefault(x => x.IdDs == id);
        pos.Active = false;

        db.SaveChanges();
    }
}