// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OptTorgWebDB.Models;

public partial class DeliveryStatus
{
    public long IdDs { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Delivery> Delivery { get; set; } = new List<Delivery>();
}