// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OptTorgWebDB.Models;

public partial class Drivers
{
    public long IdDrivers { get; set; }

    public long SeId { get; set; }

    public string License { get; set; }

    public virtual ICollection<Delivery> Delivery { get; set; } = new List<Delivery>();

    public virtual StorageEmployees Se { get; set; }

    public virtual ICollection<Sending> Sending { get; set; } = new List<Sending>();
}