// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OptTorgWebDB.Models;

public partial class Employees
{
    public long IdEmployees { get; set; }

    public long? PositionId { get; set; }

    public string Surname { get; set; }

    public string Name { get; set; }

    public string Patronomic { get; set; }

    public DateOnly? BirthDate { get; set; }

    public string Adress { get; set; }

    public string City { get; set; }

    public string Oblast { get; set; }

    public int PostIndex { get; set; }

    public string State { get; set; }

    public string Email { get; set; }

    public int WorkPhone { get; set; }

    public int Inn { get; set; }

    public string PassWord { get; set; }
    public bool Active { get; set; }

    public virtual ICollection<Delivery> DeliveryEmployeeAccept { get; set; } = new List<Delivery>();

    public virtual ICollection<Delivery> DeliveryEmployeeReceive { get; set; } = new List<Delivery>();

    public virtual Positions Position { get; set; }

    public virtual ICollection<Sending> Sending { get; set; } = new List<Sending>();

    public virtual ICollection<StorageEmployees> StorageEmployees { get; set; } = new List<StorageEmployees>();
}