// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OptTorgWebDB.Models;

public partial class MeasureUnits
{
    public long IdMu { get; set; }

    public string Name { get; set; }

    public string UslovnoeObozn { get; set; }

    public string OkeiCode { get; set; }

    public virtual ICollection<Products> Products { get; set; } = new List<Products>();
}