// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using OptTorgWeb.Classes;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace OptTorgWebDB.Models;

public partial class Packaging
{
    [Required(ErrorMessage = ErrorMessages.IsRequired)]
    public long IdPackaging { get; set; }

    [Required(ErrorMessage = ErrorMessages.IsRequired)]
    [RegularExpression(@"^[а-яА-Я]+$", ErrorMessage = ErrorMessages.OnlyRuLetters)]
    [MinLength(2, ErrorMessage = "Введенное значение слишком короткое. Минимальная длинна - 2 символа")]
    public string Type { get; set; }

    public bool Active { get; set; }

    public virtual ICollection<Products> Products { get; set; } = new List<Products>();


    public static List<Packaging> GetAllPackaging()
    {
        var db = new OptTorgDBContext();
        return db.Packaging.Where(x => x.Active == true).ToList();
    }
    public static void CreatrPackaging(Packaging p)
    {
        var db = new OptTorgDBContext();
        p.Active = true;
        db.Packaging.Add(p);
        db.SaveChanges();
    }
    public static Packaging GetPackagingById(int id)
    {
        var db = new OptTorgDBContext();
        return db.Packaging.Single(x => x.IdPackaging == id);
    }
    public static void UpdatePackaging(Packaging p)
    {
        var db = new OptTorgDBContext();
        p.Active = true;
        db.Packaging.Update(p);
        db.SaveChanges();
    }
    public static void DeletePackaging(int id)
    {
        var db = new OptTorgDBContext();
        var pos = db.Packaging.FirstOrDefault(x => x.IdPackaging == id);
        pos.Active = false;

        db.SaveChanges();
    }
    
    public static void DCascade(int id)
    {
        var db = new OptTorgDBContext();
        var strg = db.Packaging.FirstOrDefault(x => x.IdPackaging == id);

        db.Remove(strg);
        db.SaveChanges();
    }
}