// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OptTorgWebDB.Models;

public partial class Pricing
{
    public long IdPricing { get; set; }

    public double ForTonnes { get; set; }

    public double ForTonnesKm { get; set; }

    public double PogruzRazgruz { get; set; }

    public double NedogruzAvto { get; set; }

    public double Expedirovanie { get; set; }

    public double DowntimeLoading { get; set; }

    public double DowntimeUnloading { get; set; }

    public double ZaSrochnost { get; set; }

    public double ZaSpecTransport { get; set; }

    public double Other { get; set; }

    public virtual ICollection<Sending> Sending { get; set; } = new List<Sending>();
}