// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using OptTorgWeb.Classes;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace OptTorgWebDB.Models;

public partial class Pricing
{
    [Required(ErrorMessage = ErrorMessages.IsRequired)]
    public long IdPricing { get; set; }

    [Required(ErrorMessage = ErrorMessages.IsRequired)]
    [Range(0, double.MaxValue, ErrorMessage = "Значение должно быть больше или равно 0")]
    [RegularExpression(@"^-?\d+(\.\d+)?$", ErrorMessage = "Введите корректное число (разделитель - точка)")]
    public double ForTonnes { get; set; }

    [Required(ErrorMessage = ErrorMessages.IsRequired)]
    [Range(0, double.MaxValue, ErrorMessage = "Значение должно быть больше или равно 0")]
    [RegularExpression(@"^-?\d+(\.\d+)?$", ErrorMessage = "Введите корректное число (разделитель - точка)")]
    public double ForTonnesKm { get; set; }

    [Required(ErrorMessage = ErrorMessages.IsRequired)]
    [Range(0, double.MaxValue, ErrorMessage = "Значение должно быть больше или равно 0")]
    [RegularExpression(@"^-?\d+(\.\d+)?$", ErrorMessage = "Введите корректное число (разделитель - точка)")]
    public double PogruzRazgruz { get; set; }

    [Required(ErrorMessage = ErrorMessages.IsRequired)]
    [Range(0, double.MaxValue, ErrorMessage = "Значение должно быть больше или равно 0")]
    [RegularExpression(@"^-?\d+(\.\d+)?$", ErrorMessage = "Введите корректное число (разделитель - точка)")]
    public double NedogruzAvto { get; set; }

    [Required(ErrorMessage = ErrorMessages.IsRequired)]
    [Range(0, double.MaxValue, ErrorMessage = "Значение должно быть больше или равно 0")]
    [RegularExpression(@"^-?\d+(\.\d+)?$", ErrorMessage = "Введите корректное число (разделитель - точка)")]
    public double Expedirovanie { get; set; }

    [Required(ErrorMessage = ErrorMessages.IsRequired)]
    [Range(0, double.MaxValue, ErrorMessage = "Значение должно быть больше или равно 0")]
    [RegularExpression(@"^-?\d+(\.\d+)?$", ErrorMessage = "Введите корректное число (разделитель - точка)")]
    public double DowntimeLoading { get; set; }

    [Required(ErrorMessage = ErrorMessages.IsRequired)]
    [Range(0, double.MaxValue, ErrorMessage = "Значение должно быть больше или равно 0")]
    [RegularExpression(@"^-?\d+(\.\d+)?$", ErrorMessage = "Введите корректное число (разделитель - точка)")]
    public double DowntimeUnloading { get; set; }

    [Required(ErrorMessage = ErrorMessages.IsRequired)]
    [Range(0, double.MaxValue, ErrorMessage = "Значение должно быть больше или равно 0")]
    [RegularExpression(@"^-?\d+(\.\d+)?$", ErrorMessage = "Введите корректное число (разделитель - точка)")]
    public double ZaSrochnost { get; set; }

    [Required(ErrorMessage = ErrorMessages.IsRequired)]
    [Range(0, double.MaxValue, ErrorMessage = "Значение должно быть больше или равно 0")]
    [RegularExpression(@"^-?\d+(\.\d+)?$", ErrorMessage = "Введите корректное число (разделитель - точка)")]
    public double ZaSpecTransport { get; set; }

    [Required(ErrorMessage = ErrorMessages.IsRequired)]
    [Range(0, double.MaxValue, ErrorMessage = "Значение должно быть больше или равно 0")]
    [RegularExpression(@"^-?\d+(\.\d+)?$", ErrorMessage = "Введите корректное число (разделитель - точка)")]
    public double Other { get; set; }

    public bool Active { get; set; }

    public virtual ICollection<Sending> Sending { get; set; } = new List<Sending>();


    public static List<Pricing> GetAllPricing()
    {
        var db = new OptTorgDBContext();
        return db.Pricing.Where(x => x.Active == true).ToList();
    }
    public static void CreatrPricing(Pricing p)
    {
        var db = new OptTorgDBContext();
        p.Active = true;
        db.Pricing.Add(p);
        db.SaveChanges();
    }
    public static Pricing GetPricingById(int id)
    {
        var db = new OptTorgDBContext();
        return db.Pricing.Single(x => x.IdPricing == id);
    }
    public static void UpdatePricing(Pricing p)
    {
        var db = new OptTorgDBContext();
        p.Active = true;
        db.Pricing.Update(p);
        db.SaveChanges();
    }

    public static void DeletePricing(int id)
    {
        var db = new OptTorgDBContext();
        var pos = db.Pricing.FirstOrDefault(x => x.IdPricing == id);
        pos.Active = false;

        db.SaveChanges();
    }

    public static void DCascade(int id)
    {
        var db = new OptTorgDBContext();
        var strg = db.Pricing.FirstOrDefault(x => x.IdPricing == id);

        db.Remove(strg);
        db.SaveChanges();
    }
}