// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OptTorgWebDB.Models;

public partial class ProductPart
{
    public long IdPp { get; set; }

    public long BuyId { get; set; }

    public long DeliveryId { get; set; }

    public int Count { get; set; }

    public virtual Buys Buy { get; set; }

    public virtual Delivery Delivery { get; set; }
}