// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;

namespace OptTorgWebDB.Models;

public partial class ProductPart
{
    public long IdPp { get; set; }

    public long BuyId { get; set; }

    public long DeliveryId { get; set; }

    public int Count { get; set; }
    
    public bool Active { get; set; }

    public virtual Buys Buy { get; set; }

    public virtual Delivery Delivery { get; set; }

    public static List<ProductPart> GetAllProductPart()
    {
        var db = new OptTorgDBContext();
        var p = db.ProductPart
            .Include(x => x.Delivery.Transport)
            .Include(x => x.Delivery.Storage)
            .Include(x => x.Delivery.Driver.SeNavigation.EmployeeNavigation)
            .Include(x => x.Delivery.Status)
            .Include(x => x.Buy.Product)
            .Where(x => x.Active == true);

        return p.ToList();
    }
}