// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using OptTorgWeb.Classes;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace OptTorgWebDB.Models;

public partial class ProductSort
{
    [Required(ErrorMessage = ErrorMessages.IsRequired)]
    public long IdPs { get; set; }

    [Required(ErrorMessage = ErrorMessages.IsRequired)]
    [RegularExpression(@"^[а-яА-Я]+$", ErrorMessage = ErrorMessages.OnlyRuLetters)]
    [MinLength(2, ErrorMessage = "Введенное значение слишком короткое. Минимальная длинна - 2 символа")]
    public string SortName { get; set; }

    public bool Active { get; set; }

    public virtual ICollection<Products> Products { get; set; } = new List<Products>();

    public static List<ProductSort> GetAllProductSort()
    {
        var db = new OptTorgDBContext();
        return db.ProductSort.Where(x => x.Active == true).ToList();
    }
    public static void CreatrProductSort(ProductSort p)
    {
        var db = new OptTorgDBContext();
        p.Active = true;
        db.ProductSort.Add(p);
        db.SaveChanges();
    }
    public static ProductSort GetProductSortById(int id)
    {
        var db = new OptTorgDBContext();
        return db.ProductSort.Single(x => x.IdPs == id);
    }
    public static void UpdateProductSort(ProductSort p)
    {
        var db = new OptTorgDBContext();
        p.Active = true;
        db.ProductSort.Update(p);
        db.SaveChanges();
    }
    public static void DeleteProductSort(int id)
    {
        var db = new OptTorgDBContext();
        var pos = db.ProductSort.FirstOrDefault(x => x.IdPs == id);
        pos.Active = false;

        db.SaveChanges();
    }
    public static void DCascade(int id)
    {
        var db = new OptTorgDBContext();
        var strg = db.ProductSort.FirstOrDefault(x => x.IdPs == id);

        db.Remove(strg);
        db.SaveChanges();
    }
}