// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using OptTorgWeb.Classes;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace OptTorgWebDB.Models;

public partial class ProductPart
{
    [Required(ErrorMessage = ErrorMessages.IsRequired)]
    public long IdPp { get; set; }

    [Required(ErrorMessage = ErrorMessages.IsRequired)]
    public long BuyId { get; set; }

    [Required(ErrorMessage = ErrorMessages.IsRequired)]
    public long DeliveryId { get; set; }

    [Required(ErrorMessage = ErrorMessages.IsRequired)]
    [Range(1, int.MaxValue, ErrorMessage = "Значение должно быть больше 0.")]
    public int Count { get; set; }
    
    public bool Active { get; set; }

    public virtual Buys Buy { get; set; }

    public virtual Delivery Delivery { get; set; }

    public static List<ProductPart> GetAllProductPart()
    {
        var db = new OptTorgDBContext();
        var p = db.ProductPart
            .Include(x => x.Delivery.Transport)
            .Include(x => x.Delivery.Storage)
            .Include(x => x.Delivery.Driver.SeNavigation.EmployeeNavigation)
            .Include(x => x.Delivery.Status)
            .Include(x => x.Buy.Product)
            .Include(x => x.Buy.Supplier)
            .Where(x => x.Active == true);

        return p.ToList();
    }

    public static List<ProductPart> GetProductPartForDelivery(long deliveryId)
    {
        var db = new OptTorgDBContext();
        var p = db.ProductPart
            .Include(x => x.Delivery.Transport)
            .Include(x => x.Delivery.Storage)
            .Include(x => x.Delivery.Driver.SeNavigation.EmployeeNavigation)
            .Include(x => x.Delivery.Status)
            .Include(x => x.Buy.Product.Sort)
            .Include(x => x.Buy.Product.Country)
            .Include(x => x.Buy.Product.Mu)
            .Include(x => x.Buy.Product.Packing)
            .Include(x => x.Buy.Supplier)
            .Where(x => x.DeliveryId==deliveryId);

        return p.ToList();
    }

    public static void CreatrProductPart(ProductPart p)
    {
        var db = new OptTorgDBContext();
        p.Active = true;
        p.Delivery = null;
        p.Buy = null;
        
        db.ProductPart.Add(p);

        db.SaveChanges();
    }

    public static void DeleteProductPart(long id)
    {
        var db = new OptTorgDBContext();
        var pos = db.ProductPart.FirstOrDefault(x => x.IdPp == id);
        pos.Active = false;

        db.SaveChanges();
    }
    public static void DCascade(int id)
    {
        var db = new OptTorgDBContext();
        var strg = db.ProductPart.FirstOrDefault(x => x.IdPp == id);

        db.Remove(strg);
        db.SaveChanges();
    }
}