// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OptTorgWebDB.Models;

public partial class Sales
{
    public long IdSales { get; set; }

    public long ProductId { get; set; }

    public int Count { get; set; }

    public virtual ICollection<CargoInfo> CargoInfo { get; set; } = new List<CargoInfo>();

    public virtual Products Product { get; set; }
}