// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OptTorgWebDB.Models;

public partial class Sending
{
    public long IdSending { get; set; }

    public long TransportId { get; set; }

    public long DriverId { get; set; }

    public long StorageId { get; set; }

    public long EmployeesId { get; set; }

    public long SeId { get; set; }

    public long PricingId { get; set; }

    public long SsId { get; set; }

    public long CustomerId { get; set; }

    public double? ExtraOperLoading { get; set; }

    public double? ExtraOperUnloading { get; set; }

    public DateOnly? DateArrivalLoading { get; set; }

    public DateOnly? DateArrivalUnloading { get; set; }

    public DateTimeOffset? TimeExtraOperationsLoading { get; set; }

    public double? DistanceInCity { get; set; }

    public double? Distance1TypeRoad { get; set; }

    public double? Distance2TypeRoad { get; set; }

    public double? Distance3TypeRoad { get; set; }

    public string CodExpedir { get; set; }

    public double? SClientaZaUslugi { get; set; }

    public double? VoditeluZaUslugi { get; set; }

    public double? Shtraph { get; set; }

    public double? RascenkaVoditelu { get; set; }

    public double? MainTarriffs { get; set; }

    public DateTimeOffset? TimeLoading { get; set; }

    public DateTimeOffset? TimeUnloading { get; set; }

    public DateTimeOffset? DowntimeLoading { get; set; }

    public DateTimeOffset? DowntimeUnloading { get; set; }

    public double? Expedirovanie { get; set; }

    public double? ZaSrochnost { get; set; }

    public double? ZaSpecTransport { get; set; }

    public double? OtherExtraPay { get; set; }

    public string NomerDoverenosti { get; set; }

    public DateOnly? DataDoverenosti { get; set; }

    public virtual ICollection<CargoInfo> CargoInfo { get; set; } = new List<CargoInfo>();

    public virtual Customers Customer { get; set; }

    public virtual Drivers Driver { get; set; }

    public virtual Employees Employees { get; set; }

    public virtual Pricing Pricing { get; set; }

    public virtual StorageEmployees Se { get; set; }

    public virtual SendingStatus Ss { get; set; }

    public virtual Storages Storage { get; set; }

    public virtual Transport Transport { get; set; }
}