// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OptTorgWebDB.Models;

public partial class SendingStatus
{
    public long IdSs { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Sending> Sending { get; set; } = new List<Sending>();
}