// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OptTorgWebDB.Models;

public partial class Storages
{
    public long IdStorages { get; set; }

    public string Adress { get; set; }

    public string City { get; set; }

    public string Oblast { get; set; }

    public string State { get; set; }

    public int? Phone { get; set; }

    public int? Fax { get; set; }

    public virtual ICollection<Delivery> Delivery { get; set; } = new List<Delivery>();

    public virtual ICollection<Sending> Sending { get; set; } = new List<Sending>();

    public virtual ICollection<StorageEmployees> StorageEmployees { get; set; } = new List<StorageEmployees>();
}