// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OptTorgWebDB.Models;

public partial class StorageEmployees
{
    public long IdSe { get; set; }

    public long EmployeeId { get; set; }

    public long StorageId { get; set; }

    public DateOnly AdmissionDate { get; set; }

    public virtual ICollection<Drivers> Drivers { get; set; } = new List<Drivers>();

    public virtual Employees Employee { get; set; }

    public virtual ICollection<Sending> Sending { get; set; } = new List<Sending>();

    public virtual Storages Storage { get; set; }
}