// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OptTorgWebDB.Models;

public partial class Suppliers
{
    public long IdSuppliers { get; set; }

    public string Company { get; set; }

    public string Surname { get; set; }

    public string Name { get; set; }

    public string Patronymic { get; set; }

    public string Position { get; set; }

    public string Adress { get; set; }

    public string City { get; set; }

    public string Oblast { get; set; }

    public string PostIndex { get; set; }

    public string State { get; set; }

    public int? Fax { get; set; }

    public int Phone { get; set; }

    public string WebPage { get; set; }

    public int Inn { get; set; }

    public virtual ICollection<Buys> Buys { get; set; } = new List<Buys>();
}