// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OptTorgWebDB.Models;

public partial class Suppliers
{
    public long IdSuppliers { get; set; }

    public string Company { get; set; }

    public string Surname { get; set; }

    public string Name { get; set; }

    public string Patronymic { get; set; }

    public string Position { get; set; }

    public string Adress { get; set; }

    public string City { get; set; }

    public string Oblast { get; set; }

    public string PostIndex { get; set; }

    public string State { get; set; }

    public int? Fax { get; set; }

    public string Phone { get; set; }

    public string WebPage { get; set; }

    public int Inn { get; set; }
    public bool Active { get; set; }

    public virtual ICollection<Buys> Buys { get; set; } = new List<Buys>();

    public static List<Suppliers> GetAllSuppliers()
    {
        var db = new OptTorgDBContext();
        return db.Suppliers.Where(x => x.Active == true).ToList();
    }
    public static void CreatrSuppliers(Suppliers p)
    {
        var db = new OptTorgDBContext();
        p.Active = true;
        db.Suppliers.Add(p);
        db.SaveChanges();
    }
    public static Suppliers GetSuppliersById(int id)
    {
        var db = new OptTorgDBContext();
        return db.Suppliers.Single(x => x.IdSuppliers == id);
    }
    public static void UpdateSuppliers(Suppliers p)
    {
        var db = new OptTorgDBContext();
        p.Active = true;
        db.Suppliers.Update(p);
        db.SaveChanges();
    }
    public static void DeleteSuppliers(int id)
    {
        var db = new OptTorgDBContext();
        var pos = db.Suppliers.FirstOrDefault(x => x.IdSuppliers == id);
        pos.Active = false;

        db.SaveChanges();
    }
}