// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OptTorgWebDB.Models;

public partial class Transport
{
    public long IdTransport { get; set; }

    public string Name { get; set; }

    public string GosNomer { get; set; }

    public double Tonnage { get; set; }

    public bool Active { get; set; }

    public virtual ICollection<Delivery> Delivery { get; set; } = new List<Delivery>();

    public virtual ICollection<Sending> Sending { get; set; } = new List<Sending>();

    public static List<Transport> GetAllTransport()
    {
        var db = new OptTorgDBContext();
        return db.Transport.Where(x => x.Active == true).ToList();
    }
    public static void CreatrTransport(Transport p)
    {
        var db = new OptTorgDBContext();
        p.Active = true;
        db.Transport.Add(p);
        db.SaveChanges();
    }
    public static Transport GetTransportById(int id)
    {
        var db = new OptTorgDBContext();
        return db.Transport.Single(x => x.IdTransport == id);
    }
    public static void UpdateTransport(Transport p)
    {
        var db = new OptTorgDBContext();
        db.Transport.Update(p);
        db.SaveChanges();
    }
    public static void DeleteTransport(int id)
    {
        var db = new OptTorgDBContext();
        var pos = db.Transport.FirstOrDefault(x => x.IdTransport == id);
        pos.Active = false;

        db.SaveChanges();
    }
}