// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OptTorgWebDB.Models;

public partial class Transport
{
    public long IdTransport { get; set; }

    public string Name { get; set; }

    public string GosNomer { get; set; }

    public double Tonnage { get; set; }

    public virtual ICollection<Delivery> Delivery { get; set; } = new List<Delivery>();

    public virtual ICollection<Sending> Sending { get; set; } = new List<Sending>();
}